#!/bin/bash

echo "🚀 CompForge Deployment Script"
echo "=============================="

echo ""
echo "📋 Prerequisites:"
echo "1. GitHub repository with your code"
echo "2. Railway account (railway.app)"
echo "3. Vercel account (vercel.com)"
echo "4. MongoDB Atlas database"
echo "5. OpenRouter API key"
echo ""

echo "🔧 Step 1: Deploy Backend to Railway"
echo "1. Go to railway.app"
echo "2. Create new project from GitHub repo"
echo "3. Set root directory to 'backend'"
echo "4. Add these environment variables:"
echo ""
echo "NODE_ENV=production"
echo "PORT=5000"
echo "BASE_URL=https://your-backend-url.railway.app"
echo "MONGODB_URI=mongodb+srv://srivastavaananya113:Asas2003@cluster0.t8siv.mongodb.net/compforge"
echo "JWT_SECRET=your-super-secret-jwt-key-for-production"
echo "OPENROUTER_API_KEY=your-openrouter-api-key"
echo "FRONTEND_URL=https://your-frontend-url.vercel.app"
echo "CORS_ORIGIN=https://your-frontend-url.vercel.app"
echo ""

echo "🌐 Step 2: Deploy Frontend to Vercel"
echo "1. Go to vercel.com"
echo "2. Import project from GitHub"
echo "3. Set root directory to 'frontend'"
echo "4. Add environment variable:"
echo "   NEXT_PUBLIC_API_URL=https://your-backend-url.railway.app"
echo ""

echo "✅ Step 3: Update CORS"
echo "After getting frontend URL, update Railway environment variables:"
echo "FRONTEND_URL=https://your-frontend-url.vercel.app"
echo "CORS_ORIGIN=https://your-frontend-url.vercel.app"
echo ""

echo "🎉 Your CompForge app will be live!"
echo "Frontend: https://your-app.vercel.app"
echo "Backend: https://your-backend.railway.app" 